core/urls.py
from django.urls import path        
from . import views


app_name = "core"
urlpatterns = [
    
    path('', views.index , name= 'index'),
    path('qrcode/add', views.addQrcode , name= 'addQrcode'),
    path('qrcode/', views.listQrcode , name= 'listQrcode'),
    path('category/add', views.addCategory , name= 'addCategory'),
    path('category/', views.listCategory , name= 'listCategory'),
    path('menuitem/add', views.addMenuItem , name= 'addMenuItem'),
    path('menuitem/<int:id>/edit/', views.editMenuItem , name= 'editMenuItem'),
    path('menuitem/<int:id>/delete/', views.deleteMenuItem , name= 'deleteMenuItem'),
    path('menuitem/', views.listMenuItem , name= 'listMenuItem'),
    path('order/', views.listOrder , name= 'listOrder'),
    path('orderAccept/<int:id>/', views.orderAccept , name= 'orderAccept'),
    path('orderLineAccept/<int:id>/', views.orderLineAccept , name= 'orderLineAccept'),
    path('category/<int:id>/edit/', views.editCategory , name= 'editCategory'),
    path('category/<int:id>/delete/', views.deleteCategory , name= 'deleteCategory'),
    path('qrcode/<int:id>/edit/', views.editCategory , name= 'editQrcode'),
    path('qrcode/<int:id>/delete/', views.deleteQrcode , name= 'deleteQrcode'),
    

    
]

emenu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [

    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    path('customer/',include('customer.urls')),
    path('admin/',include('core.urls')),
    path('djadmin/', admin.site.urls),
    path('customer/api/', include('customer.api.urls')),
    path('',include('customer.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]


urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

import qrcode
import io
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.conf import settings
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

class MenuItem(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=False, blank=False,
                                 related_name='menu_items')
    is_active = models.BooleanField(default=True)
    media = models.ManyToManyField('Media', related_name='item_media')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def media_image(self):
        #host_id = socket.gethostbyname(socket.gethostname())
        ret = ''
        for media_file in self.media.all()[:1]:
            ret = media_file.file.url
        return ret

FILE_CHOICES = (
    ("Image", "Image"),
    ("Video", "Video"),
)

class Media(models.Model):
    type = models.CharField(max_length=10, choices=FILE_CHOICES, null=False, blank=False)
    file = models.FileField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    
class QRCode(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    qr_code_id = models.CharField(max_length=16, blank=True)
    qr_code = models.ImageField(null=False, blank=False)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def generate_qrcode(self):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=12,
            border=0,
        )
        code = settings.QR_CODE_URL 
        qr.add_data(code)
        qr.make(fit=True)
        img = qr.make_image()

        buffer = io.BytesIO()
        img.save(buffer)
        filename = 'qr_code-%s.png' % (self.id)
        filebuffer = InMemoryUploadedFile(
            buffer, None, filename, 'image/png', buffer.getbuffer().nbytes, None)
        self.qr_code.save(filename, filebuffer)

class Order(models.Model):
    qr_code = models.ForeignKey('QRCode', on_delete=models.CASCADE, null=False, blank=False, related_name='orders')
    total_quantity = models.IntegerField(default=1)
    total = models.FloatField(blank=True, null=True)
    suggestion = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=10, default="Pending")
    is_active = models.BooleanField(default=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    date_confirmed = models.DateTimeField(null=True, blank=True)

class OrderDetails(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_master')
    menu_item = models.ForeignKey('MenuItem', on_delete=models.CASCADE, null=False, blank=False, related_name='orders_menu')
    quantity = models.IntegerField(default=1)
    unit_price = models.FloatField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    status = models.CharField(max_length=10, default="Pending")
    is_active = models.BooleanField(default=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    date_confirmed = models.DateTimeField(null=True,blank=True)


class Cart(models.Model):
    qr_code = models.ForeignKey('QRCode', on_delete=models.CASCADE, related_name='cart_qrcode')
    menu_item = models.ForeignKey('MenuItem', on_delete=models.CASCADE, related_name='cart_menu')
    quantity = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now_add=True)

core/views.py
from django.shortcuts import render,redirect,reverse
from .models import *
import random, string
from django.contrib import messages
import datetime
from datetime import date
from django.contrib.auth.decorators import user_passes_test
 
# Create your views here.
@user_passes_test(lambda u: u.is_staff  )
def index(request): 

    return render(request, 'core/dashboard.html')

def addQrcode(request):
    if request.method == 'POST': 
        qr_code = QRCode()
        qr_code.name = request.POST['name']
        qr_code.description = request.POST['description']
        qr_code.qr_code_id = ''.join(random.choice(string.ascii_lowercase + string.digits) for each in range(8))
        qr_code.save()
        qr_code.generate_qrcode()
        messages.success(request, 'Table successfully Created')
        return redirect(reverse('core:listQrcode'))
    
    return render(request, 'core/addQrcode.html')

def listQrcode(request):
    qrcode = QRCode.objects.all()
    context = {
        'data' : qrcode
    }
    return render(request, 'core/listQrcode.html', context)

def addCategory(request):
    if request.method == 'POST':
        category = Category()
        category.name = request.POST['name']
        category.description = request.POST['description']
        category.save()
        messages.success(request, 'Category successfully Created')
        return redirect(reverse('core:listCategory'))
    
    return render(request, 'core/addCategory.html')

def listCategory(request):
    category = Category.objects.all()
    context = {
        'data' : category
    }
    return render(request, 'core/listCategory.html', context)

def addMenuItem(request):
    if request.method == 'POST':
        item = MenuItem()
        item.name = request.POST['name']
        item.price = request.POST['price']
        item.category = Category.objects.get(id=request.POST['category'])   
        item.description = request.POST['description']
        item.save()
        if request.FILES.getlist('media'):
            for media in request.FILES.getlist('media'):
                media_object = Media()
                media_object.type = 'Image'
                media_object.file = media
                media_object.save()
                item.media.add(media_object)
                item.save()
        messages.success(request, 'Item successfully Created')
        return redirect(reverse('core:listMenuItem'))
    category = Category.objects.all()
    context = {
        'data' : category
    }
    return render(request, 'core/addMenuItem.html', context)


def listMenuItem(request):
    item = MenuItem.objects.all()
    context = {
        'data' : item
    }
    return render(request, 'core/listMenuItem.html', context)

def editMenuItem(request,id):
    item = MenuItem.objects.get(id = id )
    if request.method == 'POST':
        
        item.name = request.POST['name']
        item.price = request.POST['price']
        item.category = Category.objects.get(id=request.POST['category'])   
        item.description = request.POST['description']
        item.save()
        
        messages.success(request, 'Item successfully Modified')
        return redirect(reverse('core:listMenuItem'))
    category = Category.objects.all()
    context = {
        'item':item,
        'data' : category
    }
    return render(request, 'core/editMenuItem.html', context)

def deleteMenuItem(request,id):
    item = MenuItem.objects.get(id = id ).delete()
    messages.success(request, 'Item successfully Deleted')
    return redirect(reverse('core:listMenuItem'))


def listOrder(request):
    order = Order.objects.filter(is_active=True)
    context = {
            'order': order,
    }
    return render(request, 'core/listOrder.html', context)

def orderAccept(request, id):
    order = Order.objects.get(id=id)
    for each in order.order_master.filter(status='Pending'):
        each.status = "Accepted"
        each.date_confirmed = datetime.datetime.now()
        each.save()
    order.status = "Accepted"
    order.date_confirmed = datetime.datetime.now()
    order.save()
    messages.success(request, 'Order Accepted')
    return redirect(request.META['HTTP_REFERER'])
    # return redirect(reverse('core:orderList'))


def orderLineAccept(request, id):
    orderline = OrderDetails.objects.get(id=id)
    orderline.status = "Accepted"
    orderline.date_confirmed = datetime.datetime.now()
    orderline.save()
    ## update order status, if there any single pending orderline does not exist
    order_status = "Accepted"
    for each in OrderDetails.objects.filter(order=orderline.order):
        if each.status == "Pending":
            order_status = "Pending"
    if order_status == "Accepted":
        order = Order.objects.get(id=orderline.order_id)
        order.status = "Accepted"
        order.date_confirmed = datetime.datetime.now()
        order.save()


    
    messages.success(request, 'Order Accepted')
    return redirect(request.META['HTTP_REFERER'])

def editCategory(request,id):
    item = Category.objects.get(id = id )
    if request.method == 'POST':
        
        item.name = request.POST['name']
        item.description = request.POST['description']
        item.save()
        
        messages.success(request, 'Item successfully Modified')
        return redirect(reverse('core:listCategory'))
    category = Category.objects.all()
    context = {
        'item':item,
        'data' : category
    }
    return render(request, 'core/editCategory.html', context)

def deleteCategory(request,id):
    item = Category.objects.get(id = id ).delete()
    messages.success(request, 'Item successfully Deleted')
    return redirect(reverse('core:listCategory'))

def editQrcode(request,id):
    item = QRCode.objects.get(id = id )
    if request.method == 'POST':
        
        item.name = request.POST['name']
        item.description = request.POST['description']
        item.save()
        
        messages.success(request, 'Item successfully Modified')
        return redirect(reverse('core:listQrcode'))
    category = Category.objects.all()
    context = {
        'item':item,
        'data' : category
    }
    return render(request, 'core/editQrcode.html', context)

def deleteQrcode(request,id):
    item = QRCode.objects.get(id = id ).delete()
    messages.success(request, 'Item successfully Deleted')
    return redirect(reverse('core:listQrcode'))

templates/core/addCategory.html
{% extends 'base.html' %}

{% block content %}


<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Add Table/Room</h1>
            </div>
            <form class="user" action="{% url 'core:addCategory' %}" method="POST">
                {% csrf_token %}
              <div class="form-group row">
               
                <div class="col-sm-6">
                  <label for="name">Name</label>
                  <input type="text" class="form-control form-control-user" onchange="ValidateName();" name="name" id="name" placeholder=Category Name" required>
                <p id="er_msg"></p>
                </div>
              </div>
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control form-control-user" rows="3" name="description" id="exampleFormControlTextarea1" placeholder="Description" required></textarea>
                
              </div>
              
              <button type="submit" class="btn btn-primary btn-user ">
                SUBMIT
              </button>
              <hr>
              
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}
{% block script%}
    <script>
        function ValidateName() {

            var name = document.getElementById('name').value;
            document.getElementById('name').value = name.trim();
            name = document.getElementById('name').value;
            {#var inValid = /\s/;#}
            {#// name = name.replace(/\s/g, '')#}
            if(name === ''){
                document.getElementById("er_msg").innerHTML ="No space please and don't leave it empty";
                document.getElementById("er_msg").style.color = "red";
                document.getElementById("name").value = "";
                return false;
            }
            else{
                document.getElementById("er_msg").innerHTML ="";
                return true;
            }

     }
    </script>
{% endblock %}

templates/core/addMenuItem.html
{% extends 'base.html' %}

{% block content %}


<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Add Item</h1>
            </div>
            <form class="user" action="{% url 'core:addMenuItem' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
              <div class="form-group row">
               
                <div class="col-sm-6">
                  <label for="name">Name</label>
                  <input type="text" class="form-control form-control-user" onchange="ValidateName();" name="name" id="name" placeholder=Item Name" required>
                <p id="er_msg"></p>
                </div>
              </div>
              <div class="form-group row">
               
                <div class="col-sm-6">
                  <label for="name">Price</label>
                  <input type="text" class="form-control form-control-user" onchange="ValidateName();" name="price" id="price" placeholder=Price Name" required>
                <p id="er_msg"></p>
                </div>
              </div>
              <div class="form-group row">
               
                <div class="col-sm-6">
                  <label for="name">Category ID</label>
                  <select class="form-control" name="category" id="category">
                    {% for each in data %}
                    <option value="{{ each.id }}">{{ each.name }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
             
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control" rows="3" name="description" id="exampleFormControlTextarea1" placeholder="Description" required></textarea>
                
              </div>
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Image</label>
                <input type="file" name="media" class="form-control" multiple>
              </div>
              
              <button type="submit" class="btn btn-primary btn-user ">
                SUBMIT
              </button>
              <hr>
              
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}
{% block script%}
    <script>
        function ValidateName() {

            var name = document.getElementById('name').value;
            document.getElementById('name').value = name.trim();
            name = document.getElementById('name').value;
            {#var inValid = /\s/;#}
            {#// name = name.replace(/\s/g, '')#}
            if(name === ''){
                document.getElementById("er_msg").innerHTML ="No space please and don't leave it empty";
                document.getElementById("er_msg").style.color = "red";
                document.getElementById("name").value = "";
                return false;
            }
            else{
                document.getElementById("er_msg").innerHTML ="";
                return true;
            }

     }
    </script>
{% endblock %}

templates/core/dashboard.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">DASHBOARD</h1>
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Orders </h6>
        <a href="{% url 'core:listOrder' %}"  style="float: right;" class="btn btn-primary btn-user" > View</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
                View pending orders
        </div>
      </div>
    </div>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
        <a href="{% url 'core:listOrder' %}"  style="float: right;" class="btn btn-primary btn-user" > View</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
                Add Categories
        </div>
      </div>
    </div>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Menu Items </h6>
        <a href="{% url 'core:addMenuItem' %}"  style="float: right;" class="btn btn-primary btn-user" >Create</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
                Add item
        </div>
      </div>
    </div>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">ROOMS/TABLE </h6>
        <a href="{% url 'core:addQrcode' %}"  style="float: right;" class="btn btn-primary btn-user" >Create</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
                Add Table
        </div>
      </div>
    </div>

  </div>


{% endblock %}

templates/core/listCategory.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Categories managemnet</h1>
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
        <a href="{% url 'core:addCategory' %}" style="float: right;" class="btn btn-primary btn-user" >Create</a>
        {% if messages %}
          
        {% for message in messages %}
        {% if message.tags == 'success' %}
            <p class="messages alert-success" style="text-align: center;">{{ message }}</p>
        {% else %}
         <p class="messages alert-danger" style="text-align: center;">{{ message }}</p>
         {% endif %}
        {% endfor %}
    
        {% endif %}
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" data-order='[[ 1, "asc" ]]' data-page-length='50' cellspacing="0">
            <thead>
              <tr>
                <th>Category ID</th> 
                <th>Category name</th>          
                <th>Description</th>
                <th>status</th>
                <th>Actions</th>
                
              </tr>
            </thead>
            
            <tbody>
            {% for each in data %}
              <tr>
                <td>{{ each.id }}</td>
                <td>{{ each.name }}</td>
                <td>{{ each.description }}</td>
                <td>{{ each.is_active }}</td>
                
                
                <td><a href="{% url 'core:editCategory' id=each.id  %}" class="btn btn-warning btn-circle btn-sm">
                    <i class="fas fa-edit"></i>
                  </a>
                    <a href="{% url 'core:deleteCategory' id=each.id  %}" class="btn btn-danger btn-circle btn-sm" onclick="return confirm('Are you sure you want to delete this?')">
                    <i class="fas fa-trash"></i>
                  </a>
                </td>
                
              </tr>
              <div class="modal fade" id="myModal{{each.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" id="{{each.id}}" >
                  <div class="modal-content" >
                    <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel">  <small>{{ each.name }}</small></h4>
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                     
                    
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>


{% endblock %}

templates/core/listMenuItem.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Added Menu Items</h1>
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Menu </h6>
        <a href="{% url 'core:addMenuItem' %}" style="float: right;" class="btn btn-primary btn-user" >Create</a>
        {% if messages %}
          
        {% for message in messages %}
        {% if message.tags == 'success' %}
            <p class="messages alert-success" style="text-align: center;">{{ message }}</p>
        {% else %}
         <p class="messages alert-danger" style="text-align: center;">{{ message }}</p>
         {% endif %}
        {% endfor %}
    
        {% endif %}
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" data-order='[[ 1, "asc" ]]' data-page-length='50' cellspacing="0">
            <thead>
              <tr>
                <th>Menu name</th>          
                <th>Description</th>
                <th>Category</th>
                <th>status</th>
                <th>Actions</th>
                
              </tr>
            </thead>
            
            <tbody>
            {% for each in data %}
              <tr>
                <td>{{ each.name }}</td>
                <td>{{ each.description }}</td>
                <td>{{ each.category.name }}</td>
                <td>{{ each.is_active }}</td>
                
                
                <td><a href="{% url 'core:editMenuItem' id=each.id  %}" class="btn btn-warning btn-circle btn-sm">
                    <i class="fas fa-edit"></i>
                  </a>
                    <a href="{% url 'core:deleteMenuItem' id=each.id  %}" class="btn btn-danger btn-circle btn-sm" onclick="return confirm('Are you sure you want to delete this?')">
                    <i class="fas fa-trash"></i>
                  </a>
                </td>
                
              </tr>
              <div class="modal fade" id="myModal{{each.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" id="{{each.id}}" >
                  <div class="modal-content" >
                    <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel">QR CODE : <small>{{ each.name }}</small></h4>
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                     
                    </div>
                    <div class="modal-body text-center pagination-centered">
                      <img src="{{ each.qr_code.url }}"/>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>


{% endblock %}

templates/core/listQrcode.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Rooms / Table Management</h1>
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Rooms/Table</h6>
        <a href="{% url 'core:addQrcode' %}" style="float: right;" class="btn btn-primary btn-user" >Create</a>
        {% if messages %}
          
        {% for message in messages %}
        {% if message.tags == 'success' %}
            <p class="messages alert-success" style="text-align: center;">{{ message }}</p>
        {% else %}
         <p class="messages alert-danger" style="text-align: center;">{{ message }}</p>
         {% endif %}
        {% endfor %}
    
        {% endif %}
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" data-order='[[ 1, "asc" ]]' data-page-length='50' cellspacing="0">
            <thead>
              <tr>
                <th>Table-ID</th>
                <th>Identifier Name</th>
                <th>Description</th>
                <th>Qr-Code</th>
                <th>Actions</th>
                
              </tr>
            </thead>
            
            <tbody>
            {% for each in data %}
              <tr>
                <td>{{ each.qr_code_id }}</td>
                <td>{{ each.name }}</td>
                <td>{{ each.description }}</td>
                <td><a href="{{ each.qr_code.url }}" target="blank" class="btn btn-success btn-circle btn-sm" data-toggle="modal" data-target="#myModal{{each.id}}">
                    <i class="fas fa-eye"></i>
                  </a>
                  <a href="#"  class="btn btn-info btn-circle btn-sm">
                    <i class="fas fa-download"></i>
                  </a>
                </td>
                <td><a href="{% url 'core:editQrcode' id=each.id  %}" class="btn btn-warning btn-circle btn-sm">
                    <i class="fas fa-edit"></i>
                  </a>
                    <a href="{% url 'core:deleteQrcode' id=each.id  %}" class="btn btn-danger btn-circle btn-sm" onclick="return confirm('Are you sure you want to delete this?')">
                    <i class="fas fa-trash"></i>
                  </a>
                </td>
                
              </tr>
              <div class="modal fade" id="myModal{{each.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" id="{{each.id}}" >
                  <div class="modal-content" >
                    <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel">QR CODE : <small>{{ each.name }}</small></h4>
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                     
                    </div>
                    <div class="modal-body text-center pagination-centered">
                      <img src="{{ each.qr_code.url }}"/>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <!--<button type="button" class="btn btn-primary">Save changes</button>-->
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>


{% endblock %}