core/urls.py
from django.urls import path        
from . import views


app_name = "core"
urlpatterns = [
    
    path('', views.index , name= 'index'),
    path('qrcode/add', views.addQrcode , name= 'addQrcode'),
    path('qrcode/', views.listQrcode , name= 'listQrcode'),
    path('category/add', views.addCategory , name= 'addCategory'),
    path('category/', views.listCategory , name= 'listCategory'),
    path('menuitem/add', views.addMenuItem , name= 'addMenuItem'),
    path('menuitem/<int:id>/edit/', views.editMenuItem , name= 'editMenuItem'),
    path('menuitem/<int:id>/delete/', views.deleteMenuItem , name= 'deleteMenuItem'),
    path('menuitem/', views.listMenuItem , name= 'listMenuItem'),
    path('order/', views.listOrder , name= 'listOrder'),
    path('orderAccept/<int:id>/', views.orderAccept , name= 'orderAccept'),
    path('orderLineAccept/<int:id>/', views.orderLineAccept , name= 'orderLineAccept'),
    path('category/<int:id>/edit/', views.editCategory , name= 'editCategory'),
    path('category/<int:id>/delete/', views.deleteCategory , name= 'deleteCategory'),
    path('qrcode/<int:id>/edit/', views.editCategory , name= 'editQrcode'),
    path('qrcode/<int:id>/delete/', views.deleteQrcode , name= 'deleteQrcode'),
    

    
]

customer/urls.py
from django.urls import path        
from . import views

app_name = "customer"

urlpatterns = [
    path('', views.Index , name= 'index'),
    path('main', views.main , name= 'main'),
    path('addtocart/<int:id>/', views.addToCart , name= 'addToCart'),
    path('cart/', views.myCart , name= 'cart'),
    path('placeOrder/', views.placeOrder , name= 'placeOrder'),
    path('placeOrder/', views.placeOrder , name= 'placeOrder'),
    path('success/', views.success , name= 'success'),
    path('filter/<int:id>/', views.filterCategory , name= 'filterCategory'),
    path('eg', views.eg , name= 'eg'),
    path('bs', views.bs , name= 'bs'),
    path('erf', views.erf , name= 'erf'),
    path('ers', views.ers , name= 'ers'),
    
]

emenu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [

    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    path('customer/',include('customer.urls')),
    path('admin/',include('core.urls')),
    path('djadmin/', admin.site.urls),
    path('customer/api/', include('customer.api.urls')),
    path('',include('customer.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]


urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base2.html
{% load static %}
{% static "images" as baseUrl %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Menu</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/pricing/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      #main{
        background: rgb(239, 241, 240);
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.5/examples/pricing/pricing.css" rel="stylesheet">
  </head>
  <body>
    <div id="main" class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">eMenu</h5>

  
  <a class="btn btn-outline-primary" href="{% url 'customer:cart' %}">My Bag</a>
</div>
<style>
  body {
    font-family: "Lato", sans-serif;
    background:rgb(184, 233, 233);
  }
  
  .sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
  }
  
  .sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }
  
  .sidenav a:hover {
    color: #f1f1f1;
  }
  
  .sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
  }
  
  @media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
  }
  </style>
  </head>
  <body >
  

  

  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
  
  <script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
  }
  
  function closeNav() {
    document.getElementById("mySidenav").style.width = "0px";
  }
  </script>
  

  {% block content %}{% endblock %}




  {% block script %} {% endblock %}
</body>
</html>

templates/base4.html
{% load static %}

<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
     <!-- Site Metas -->
    <title>eMenu Restaurant</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'customer/images/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'customer/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'customer/css/bootstrap.min.css' %}">    
	<!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'customer/css/style.css' %}">    
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'customer/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'customer/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body >
	<!-- Start header -->
	<header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#slides">
					<img src="{% static 'customer/images/logo.webp' %}" alt="" width="40px"> eMenu
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbars-rs-food">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active"><a class="nav-link" href="{% url 'customer:index'  %}">Home</a></li>
					
						<li class="nav-item"><a class="nav-link" href="{% url 'customer:cart' %}">My Bag</a></li>
						
						 
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- End header -->

  	

	
		
    {% block content %}
    
    
    {% endblock %}




    




<a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>
{% block script %} {% endblock %}
<!-- ALL JS FILES -->
<script src="{% static 'customer/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'customer/js/popper.min.js' %}"></script>
<script src="{% static 'customer/js/bootstrap.min.js' %}"></script>
<!-- ALL PLUGINS -->
<script src="{% static 'customer/js/jquery.superslides.min.js' %}"></script>
<script src="{% static 'customer/js/images-loded.min.js' %}"></script>
<script src="{% static 'customer/js/isotope.min.js' %}"></script>
<script src="{% static 'customer/js/baguetteBox.min.js' %}"></script>
<script src="{% static 'customer/js/form-validator.min.js' %}"></script>
<script src="{% static 'customer/js/contact-form-script.js' %}"></script>
<script src="{% static 'customer/js/custom.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base3.html' %}
{% load static %}

{% block nav %}
<!-- Start header -->
<header class="top-navbar">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#slides">
        <img src="{% static 'customer/images/logo.webp' %}" alt="" width="40px"> eMenu
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbars-rs-food">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a class="nav-link" href="{% url 'customer:index' %}"><i class="bi bi-house-door-fill"></i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z"/>
            <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
          </svg>&nbsp;Home</a></li>
         
          
           
        </ul>
      </div>
    </div>
  </nav>
</header>
<!-- End header -->
{% endblock %}

{% block boot %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

{% endblock %}
{% block content %}

<!-- Original -->


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">CART</h1>
  </div>

  <!--Main layout-->
  <main>
    <div class="container">
                <div class="panel-heading">
                  
                  
                </div>
      <!--Section: Block Content-->
      <section class="mt-5 mb-4">

        <!--Grid row-->
        <div class="row">
          

          <!--Grid column-->
          <div class="col-lg-8">
            

            <!-- Card -->
            <div class="card wish-list mb-4">
              <div class="panel-title">
                <div class="row">
                  
                  <div class="col-xs-6"><br>
                    <h5>
                      &nbsp;&nbsp;&nbsp;
                      &nbsp;                      
                      <i class="bi bi-cart-check"></i>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-check" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                            <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                          </svg>  eMenu Cart</h5>
                  </div>
                  <li class="btn"><br>

                     <a class="btn btn-primary" href="{% url 'customer:index' %}" >
                    <span class="glyphicon glyphicon-share-alt"></span>&nbsp;Continue shopping</a></li>

                </div>
                <br>
              </div>
              <div class="card-body">

            <!--cart loop start here-->
            <!-- <form action="{% url 'customer:placeOrder'  %}" method="POST">
              {% csrf_token %} -->
            {% for each in cart %}
                <div class="row mb-4">
                  <div class="col-md-5 col-lg-3 col-xl-3">
                    <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                      <img class="img-fluid w-100"
                        src="{{each.menu_item.media_image}}" alt="Sample">
                      <a href="#!">
                        
                      </a>
                    </div>
                  </div>
                  <div class="col-md-7 col-lg-9 col-xl-9">
                    <div>
                      <div class="d-flex justify-content-between">
                        <div>
                          <h5>{{each.menu_item.name}}</h5>
                          <p class="mb-3 text-muted text-uppercase small">{{each.menu_item.description}}</p>
                          <!-- <p class="mb-2 text-muted text-uppercase small">Color: blue</p>
                          <p class="mb-3 text-muted text-uppercase small">Size: M</p> -->
                        </div>
                        <div>
                          <div class="def-number-input number-input safari_only mb-0 w-100">
                            <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()"
                              class="btn btn-default btn-number"> 
                              <span class="glyphicon glyphicon-minus"></span>
                            </button>&nbsp;
                            <input class="btn btn-default btn-number" min="1" name="quantity" id="qty" value="{{each.quantity}}" type="number">
                            &nbsp;<button onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
                              class="btn btn-default btn-number"> 
                              <span class="glyphicon glyphicon-plus"></span>
                            </button>
                          </div>
                          <small id="passwordHelpBlock" class="form-text text-muted text-center">
                          </small>
                        </div>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <div>
                          <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i
                              class="fas fa-trash-alt mr-1"></i> Remove item </a>
                          
                        </div>
                        <input type="hidden" name="price" id="price" value="{{each.menu_item.price}}" >
                        <p class="mb-0"><span><strong>{{each.menu_item.price}}</strong></span></p>
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="mb-4">
                {% endfor %}
            <!--cart loop end here-->
                
                <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i>Adding
                  items to your cart does not mean booking them.</p>

              </div>
            </div>
            <!-- Card -->

             

            
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4">

            <!-- Card -->
            <div class="card mb-4">
              <div class="card-body">

                <h5 class="mb-3">The total amount of</h5>

                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                    Item  Price
                    <span id="itemprice">$53.98</span>
                  </li>
                  
                  <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                    <div>
                      <strong>The total amount of</strong>
                      <strong>
                        <p class="mb-0">(including VAT)</p>
                      </strong>
                    </div>
                    <span id="total"><strong>$53.98</strong></span>
                  </li>
                </ul>

                <a href="{% url 'customer:placeOrder'  %}"  class="btn btn-primary btn-block waves-effect waves-light">Order Now</a>

              </div>
            </div>
            
            <!-- Card -->

            <!-- Card -->
            <div class="card mb-4">
              <div class="card-body">

                <a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#"
                  aria-expanded="false" aria-controls="collapseExample">
                  Add a discount code (optional)
                  <span><i class="fas fa-chevron-down pt-1"></i></span>
                </a>

                <div class="collapse" id="collapseExample">
                  <div class="mt-3">
                    <div class="md-form md-outline mb-0">
                      <input type="text" id="discount-code" class="form-control font-weight-light"
                        placeholder="Enter discount code">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Card -->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Block Content-->

    </div>
  </main>
  
  <!--Main layout-->
{% endblock %}

templates/cart2.html
{% extends 'base4.html' %}

{% block content %}

<div class="container" style="margin-top: 20px;" >
	<div class="row">
		<div class="col-xs-8">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6"><br>
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
							</div>
							<div class="col-xs-6">
								<br><a href="{% url 'customer:index'  %}" class="btn btn-primary btn-block waves-effect waves-light">go to
									<span class="glyphicon glyphicon-share-alt"></span> Continue shopping</a>
								
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
					{% for each in cart %}
					<div class="row">
						<div class="col-xs-2"><img class="img-responsive" src="{{each.menu_item.media_image}}">
						</div>
						<div class="col-xs-4">
							<h4 class="product-name"><strong>{{each.menu_item.name}}</strong></h4><h4><small>{{each.menu_item.description}}</small></h4>
						</div>
						<div class="col-xs-6">
							<div class="col-xs-6 text-right">
								<h6><strong>{{each.menu_item.price}} <span class="text-muted">x</span></strong></h6>
							</div>
							<div class="col-xs-4">
								<input type="text" class="form-control input-sm" value="1">
							</div>
							<div class="col-xs-2">
								<button type="button" class="btn btn-link btn-xs">
									<span class="glyphicon glyphicon-trash"> </span>
								</button>
							</div>
						</div>
					</div>
					<hr>
					{% endfor %}
					<hr>
					<div class="row">
						<div class="text-center">
							<div class="col-xs-9">
								<h6 class="text-right">Added items?</h6>
							</div>
							
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Total <strong>$50.00</strong></h4>
						</div>
						<div class="col-xs-3">
							<a href="{% url 'customer:placeOrder'  %}" class="btn btn-primary btn-block waves-effect waves-light">go to
								checkout</a>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 
{% endblock %}

templates/home.html
{% extends 'base.html'%}

{% block content %}
{% csrf_token %}

<h1>Helloworrld</h1>

{% endblock %}

templates/index.html
{% extends 'base2.html' %}

{% block content %}
<div id="mySidenav" class="sidenav">
  <h3>eMenu</h3>
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  {% for cat in category %}
  <a href="{% url 'customer:filterCategory' cat.id  %}">{{ cat.name }}</a>
  {% endfor %}
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Book your menu now</h1>
  <p class="lead"> Everything made simple at your hand</p>
</div>

<div class="container">
  
  <div class="card-deck mb-3 text-center">
    
    {% for menu in emenu %}
    
    <div class="card mb-4 shadow-sm">
     
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{menu.name}}</h4>
      </div>
      <div class="card-body">
        
        <ul class="list-unstyled mt-3 mb-4">
          <img src="{{menu.media_image}}" width="50%">
        </ul>
         <h1 class="card-title pricing-card-title">₹{{menu.price}} <small class="text-muted">/ mo</small></h1>
          <!-- <form action="api/cart/" method="POST">
         {% csrf_token %} -->
        <input type="hidden" name="qr_code" value="hjws5tbp" id="">
        <input type="hidden" name="menuitem" value="{{ menu.id }}" id="menuitem">
        <input type="hidden" name="quantity" value=1 id="">
         <a href="{% url 'customer:addToCart' menu.id  %}" class="btn btn-lg btn-block btn-outline-primary" id="btncart">Add To Cart</a>
        
      </div>
      
    </div>
  
    {% endfor %}
  </div>
  

</div>
{% endblock %}

templates/sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon rotate-n-15">
        </div>
        <div class="w-75"><img class="img-fluid" ></div>
    </a>

     <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "core:index" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
    <hr class="sidebar-divider my-0">
    
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "core:listCategory" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Category</span></a>
    </li>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url 'core:listQrcode' %} ">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>QR code</span></a>
    </li>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "core:listMenuItem" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Menu</span></a>
    </li>
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "core:listOrder" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Order</span></a>
    </li>
     <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "customer:index" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Customer view</span></a>
    </li>

    <!-- Heading -->
    <div class="sidebar-heading">
       
    </div>
    <!-- Divider -->
    <hr class="sidebar-divider">


    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>